trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - master
      - release*
  paths:
    exclude:
      - README.md

pr:
  - master
  - develop

variables:
  repository: 'focal-freedom-236620/test-runner'
  buildTag: $(Build.BuildId)
  imageTag:

jobs:
  - job: TestRunner
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - script: |
          if [[ $(ref) == refs/tags* ]]; then
            TAG=$(echo $(ref) | sed "s|refs/tags/v||g")
            echo "##vso[task.setvariable variable=imageTag]$TAG"
          else
            LATESTTAG=$(git tag | tail -1)
            LATESTVERS=${LATESTTAG#?}
            if [ -z "$LATESTVERS" ]; then LATESTVERS=0.0.0; fi
            echo "##vso[task.setvariable variable=imageTag]$LATESTVERS-b$(buildTag)"
          fi
          echo $(imageTag)
        displayName: 'Set image tag'
      - task: Docker@2
        displayName: 'Docker build'
        inputs:
          containerRegistry: 'Edgeworx GCP'
          repository: $(repository)
          command: 'build'
          Dockerfile: "Dockerfile"
          tags: |
            $(buildTag)
            $(imageTag)
            latest

      - task: Docker@2
        displayName: 'Docker push'
        inputs:
          containerRegistry: 'Edgeworx GCP'
          repository: $(repository)
          command: 'push'
          Dockerfile: "Dockerfile"
          tags: |
            $(buildTag)
            $(imageTag)
            latest

      - script: |
          echo "gcr.io/${REPOSITORY}:$(imageTag)" > $(Build.ArtifactStagingDirectory)/docker-image.txt
        displayName: 'Save Docker image name to artifact'

      - task: PublishPipelineArtifact@0
        displayName: 'Publish Docker image name artifact'
        inputs:
          artifactName: 'docker-image.txt'
          targetPath: $(Build.ArtifactStagingDirectory)/docker-image.txt
