trigger:
  tags:
    include:
      - v.*
  branches:
    include:
      - develop
      - master
      - release
  paths:
    exclude:
      - README.md

pr:
  - master

variables:
  repository: 'focal-freedom-236620/test-runner'
  type: $(Build.SourceBranchName)
  commit: $(Build.SourceVersion)

jobs:
  - job: TriggerOtherJobs
    pool: server

    steps:

      - task: InvokeRESTAPI@1
        displayName: 'Trigger platform job'
        inputs:
          connectionType: 'connectedServiceName'
          serviceConnection: 'Pipelines'
          method: 'GET'
          urlSuffix: '/edgeworx/_apis/build/builds?api-version=5.0'
          waitForCompletion: 'false'