trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - master
      - release*
  paths:
    exclude:
      - README.md

pr:
  - master
  - develop

variables:
  repository: 'focal-freedom-236620/test-runner'
  buildTag: $(Build.BuildNumber)

jobs:
  - job: TestRunner
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - task: Docker@2
        displayName: 'Docker build'
        inputs:
          containerRegistry: 'Edgeworx GCP'
          repository: $(repository)
          command: 'build'
          Dockerfile: "Dockerfile"
          tags: |
            $(Build.BuildNumber)
            latest

      - task: Docker@2
        displayName: 'Docker push'
        inputs:
          containerRegistry: 'Edgeworx GCP'
          repository: $(repository)
          command: 'push'
          Dockerfile: "Dockerfile"
          tags: |
            $(Build.BuildNumber)
            latest

      - script: |
          echo "cat gcr.io/${REPOSITORY}:$(Build.BuildNumber) > $(Build.ArtifactStagingDirectory)/docker-image.txt"
          cat "gcr.io/${REPOSITORY}:$(Build.BuildNumber)" > $(Build.ArtifactStagingDirectory)/docker-image.txt
        displayName: "Save Docker image name to artifact"

      - task: PublishPipelineArtifact@0
          inputs:
            artifactName: 'docker-image.txt'
            targetPath: $(Build.ArtifactStagingDirectory)/docker-image.txt
