apiVersion: v1
kind: ServiceAccount
metadata:
  name: svacc-test-runner
  namespace: iofog
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb-iofog-kubelet-{{ .Release.Namespace | default .Values.defaultNamespace }}
subjects:
  - kind: ServiceAccount
    name: svacc-test-runner
    namespace: iofog
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: test-runner
  namespace: iofog
  labels:
    name: test-runner
  annotations:
    "helm.sh/hook": test-success
spec:
  serviceAccountName: svacc-test-runner
  initContainers:
    - name: test-kubeconfig
      image: bitnami/kubectl:latest
      command: ['bash', '-c']
      args:
        - |
          tail -f /dev/null
    - name: get-service-ips
      image: bitnami/kubectl:latest
      command: ['bash', '-c']
      args:
        - |
          echo "Retrieving connector public IP and port..."
          until [[ -n "${CONNECTOR_IP}" ]]; do
            CONNECTOR_IP=$(kubectl get svc connector -o jsonpath={.status.loadBalancer.ingress[0].ip})
            sleep 2
          done
          CONN_IP_PORT=$(kubectl get svc connector -o jsonpath='{.status.loadBalancer.ingress[0].ip}:{.spec.ports[0].port}')
          echo -n "${CONN_IP_PORT}" > /conf/connector.conf

          echo "Retrieving controller public IP and port..."
          until [[ -n "${CONTROLLER_IP}" ]]; do
            CONTROLLER_IP=$(kubectl get svc controller -o jsonpath={.status.loadBalancer.ingress[0].ip})
            sleep 2
          done
          CTRL_IP_PORT=$(kubectl get svc controller -o jsonpath='{.status.loadBalancer.ingress[0].ip}:{.spec.ports[0].port}')
          echo -n "${CTRL_IP_PORT}" > /conf/controller.conf

          touch /conf/id_ecdsa
          cp -f -H /secrets/id_ecdsa /conf

          cp -f -H /secrets/agents.conf /conf
          # Insert newline at the end of /conf/agents.conf in case there is none
          if [[ -f "/tmp/agents.conf" ]]; then
            [[ ! $(tail -c1 /conf/agents.conf | wc -l) -gt 0 ]] && echo >> /conf/agents.conf
          else
            touch /conf/agents.conf
          fi
      volumeMounts:
        - name: config-volume
          mountPath: /conf
          readOnly: false
#        - name: secrets-volume
#          mountPath: /secrets
#          readOnly: true
  containers:
    - name: test-runner
      image: gcr.io/focal-freedom-236620/test-runner:lkrcal
      volumeMounts:
        - name: config-volume
          mountPath: /conf
          readOnly: true
  volumes:
    - name: config-volume
      emptyDir: {}
#    - name: secrets-volume
#      projected:
#        sources:
#          - secret:
#              name: test-secret
#              items:
#                - key: privateKey
#                  path: id_ecdsa
#                - key: URI
#                  path: agents.conf
  restartPolicy: Never
